Data logger tool
analogdevicesinc/scopy pull request #1209
Opened 2022-03-10 09:22 UTC by IonutMuthi

Adding data logger tool

2022-04-05 08:23 UTC, adisuciu requested changes

2022-04-05 08:23 UTC, adisuciu commented on src/customScale.cpp
> +    if(int(num) == 0) {return -1; }
spacings

2022-04-05 11:04 UTC, AlexandraTrifan commented on src/gui/customcolqgridlayout.cpp
> +		colCount = availableWidth / width - 1;
what happens when width == 1? we'll get some undefined behaviour..

2022-04-05 11:04 UTC, AlexandraTrifan commented on src/gui/customcolqgridlayout.cpp
> +			colCount = availableWidth / m_widgetList.at(0)->width() - 1;
same as above, I guess

2022-04-05 11:07 UTC, AlexandraTrifan commented on src/gui/datalogger.cpp
> +void DataLogger::atteptDataLogging(){
typo in function name

2022-04-06 14:16 UTC, AlexandraTrifan requested changes

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/datalogger/datalogger_api.cpp
> +	Q_EMIT dataLogger->PrecisionChanged(precision);
can this be lowerCamelCase like all the others?

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/datalogger/datalogger_api.cpp
> +	Q_EMIT dataLogger->RecordingIntervalChanged(interval);
same as above

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/datalogger/dataloggergenericmenu.cpp
> +	default:throw std::runtime_error("Invalid INDEX");
are we handling the thrown error or Scopy will just crash?

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/dataloggermodel.h
> +	void distroyChannel(QString name);
typo in function name?

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/gui/channel_manager.cpp
> +        ch->setShortName(shortName + QString(" %1").arg(chId + 1));
formatting is still not good

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/gui/dataloggercontroller.cpp
> +void DataLoggerController::distroyChannel(QString name)
typo in function name?

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/gui/dataloggerview.cpp
> +	dataLogginBrowseBtn = new QPushButton("Browse");
missing character in name?

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/lcdNumber.hpp
> +            unsigned getPrecision();
bad indent

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/sismograph.hpp
> +        void dataChanged(std::vector<double> data);
bad indent

2022-04-06 14:16 UTC, AlexandraTrifan commented on src/tool.cpp
> +        run_button->setChecked(false);
bad indent

2022-05-17 12:54 UTC, merged