Dev tutorial improvements
analogdevicesinc/scopy pull request #1448
Opened 2023-08-22 12:43 UTC by Andrei-Fabian-Pop

Add visual improvements to the tutorial

2023-09-05 14:41 UTC, bindea-cristian requested changes

2023-09-05 14:41 UTC, bindea-cristian commented on gui/CMakeLists.txt
> +target_include_directories(${PROJECT_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include/${SCOPY_MODULE} ${QWT_INCLUDE_DIRS})
Same error here, please remember to add the ${Boost_INCLUDE_DIRS} variable back in to prevent MacOS errors

2023-09-05 14:41 UTC, bindea-cristian commented on gui/CMakeLists.txt
> -find_package(Boost COMPONENTS system filesystem thread chrono REQUIRED)
You should add back the search for Boost, otherwise you will get an error on MacOS

2023-09-05 14:41 UTC, bindea-cristian commented on gui/CMakeLists.txt
> +	${QWT_LIBRARIES}
Same here, missing variable: ${Boost_LIBRARIES}

2023-09-06 09:34 UTC, bindea-cristian approved these changes

2023-09-08 14:12 UTC, adisuciu requested changes

2023-09-08 14:12 UTC, adisuciu commented on gui/CMakeLists.txt
> +		${CMAKE_CURRENT_SOURCE_DIR}include/${SCOPY_MODULE}/
You lost ${CMAKE_CURRENT_SOURCE_DIR}include/${SCOPY_MODULE}/widgets here ..

2023-09-08 16:17 UTC, merged