Dev: Add commandq to iiowidgets
analogdevicesinc/scopy pull request #1548
Opened 2024-02-19 09:43 UTC by Andrei-Fabian-Pop

Add 2 new data strategies for manipulating channel and device data through iioutils/commandqueue. Also add possibility of having const data for optional data, meaning that the optional data does not have to always be read through iio.

2024-02-20 08:10 UTC, adisuciu requested changes

2024-02-20 08:10 UTC, adisuciu commented on iio-widgets/src/datastrategy/cmdqdeviceattrdatastrategy.cpp
> +		IioDeviceAttributeRead *tcmd = dynamic_cast<IioDeviceAttributeRead *>(cmd);
This lambda is pretty long .. should it be mvoed to a separate function ?

2024-02-20 08:10 UTC, adisuciu commented on iio-widgets/src/datastrategy/cmdqdeviceattrdatastrategy.cpp
> +		if(!m_recipe.constDataOptions.isEmpty()) {
Can this logic be simplified ?

2024-02-20 08:10 UTC, adisuciu commented on iio-widgets/src/datastrategy/cmdqchannelattrdatastrategy.cpp
> +		IioChannelAttributeRead *tcmd = dynamic_cast<IioChannelAttributeRead *>(cmd);
This lambda is pretty long. Should it be moved to a function ?

2024-02-20 08:10 UTC, adisuciu commented on iio-widgets/src/datastrategy/cmdqchannelattrdatastrategy.cpp
> +		if(tcmd->getReturnCode() < 0) {
Can this logic be simplified ?

2024-02-23 07:46 UTC, AlexandraTrifan commented on iio-widgets/src/iiowidgetfactory.cpp
> +		} else {
Do you still need to pass the command queue as a constructor param? After the last changes the recipe has a reference to the Connection obj, so it also has a reference to the command queue.

2024-02-26 09:45 UTC, AlexandraTrifan approved these changes

2024-03-05 13:48 UTC, adisuciu approved these changes

2024-03-06 08:50 UTC, merged