Dev datamonitor v1
analogdevicesinc/scopy pull request #1582
Opened 2024-03-20 16:04 UTC by IonutMuthi

Data logger version 2.0 first draft

2024-03-21 10:10 UTC, adisuciu requested changes

2024-03-21 10:10 UTC, adisuciu commented on plugins/datamonitor/CMakeLists.txt
> +	       libm2k::libm2k
There is no dependency to libm2k in this plugin

2024-03-21 10:10 UTC, adisuciu commented on plugins/datamonitor/CMakeLists.txt
> +	       ${GLIB_LINK_LIBRARIES}
There should be no dependency to GLIB in thisn plugin ..

2024-03-21 10:10 UTC, adisuciu commented on plugins/datamonitor/test/tst_pluginloader.cpp
> +void TST_BareMinimum::fileExists()
This test is outdated. It should use your own plugin .so and should be named accordingly.

2024-03-21 12:24 UTC, AlexandraTrifan commented on plugins/datamonitor/include/datamonitor/datamonitor.h
> +	libm2k::context::Context *libm2k_context;
are we using the libm2k context anywhere?

2024-03-21 12:25 UTC, AlexandraTrifan commented on plugins/datamonitor/src/datamonitor.cpp
> +#include <libm2k/contextbuilder.hpp>
same as previous comments, libm2k is not used here

2024-03-21 12:27 UTC, AlexandraTrifan commented on plugins/datamonitor/src/datamonitortool.cpp
> +	openLatMenuBtn = new OpenLastMenuBtn(dynamic_cast<MenuHAnim *>(tool->rightContainer()), false, this);
typo? shoule be openLastMenuBtn across the plugin

2024-03-21 12:32 UTC, AlexandraTrifan commented on plugins/datamonitor/src/datamonitor.cpp
shouldn't this file be called datamonitorplugin.cpp for consistency across plugins?

2024-03-21 13:08 UTC, AlexandraTrifan commented on plugins/CMakeLists.txt
It seems like you're missing some destructors and need to do some object cleanup.

2024-03-27 12:29 UTC, adisuciu approved these changes

2024-03-28 05:41 UTC, merged