Scopy for armhf
analogdevicesinc/scopy pull request #1602
Opened 2024-04-10 08:52 UTC by bindea-cristian

Added: 
 - cross compile toolchain
 - sysroot configuration script
 - Qt cross compile script
 - cross compile Scopy dependencies
 - docker image building script
 - github workflow that cross compiles Scopy and generates an Scopy.AppImage artifact

2024-04-16 14:50 UTC, adisuciu requested changes

2024-04-16 14:50 UTC, adisuciu commented on ci/kuiper/scopy.desktop
> +Version=1.0
V2.0

2024-04-16 14:50 UTC, adisuciu commented on ci/kuiper/create_sysroot.sh
> +export DEBIAN_FRONTEND=noninteractive
Move this to a file ?

2024-04-16 14:50 UTC, adisuciu commented on ci/kuiper/build_scopy_kuiper.sh
>  instal_apt() {
typo

2024-04-19 14:20 UTC, AlexandraTrifan commented on ci/kuiper/build_scopy_kuiper.sh
> +IIOEMU_BRANCH=master
could we change the reference to "main"? (i updated the default branch on iio-emu to be main now)
we should do this for all that apply

2024-04-23 11:49 UTC, adisuciu approved these changes

2024-04-23 13:24 UTC, AlexandraTrifan approved these changes

2024-04-23 14:37 UTC, adisuciu commented
@Adrian-Stanea  can you test this ?

2024-04-25 07:51 UTC, Adrian-Stanea commented
Tested [this AppImage](https://github.com/analogdevicesinc/scopy/actions/runs/8799696718/artifacts/1439168392) and no issues were found.

2024-04-25 07:52 UTC, Adrian-Stanea approved these changes
Tested [this AppImage](https://github.com/analogdevicesinc/scopy/actions/runs/8799696718/artifacts/1439168392) and no issues were found.

2024-04-25 12:35 UTC, merged