bufferpreviewer: fixed rolling mode bug
analogdevicesinc/scopy pull request #1611
Opened 2024-04-23 05:10 UTC by IonutMuthi

data limit now has min and max value instead of beeing the absolte diff between two values
 use lower and upper axis bound instead of axis min and max value on drag to account for zoom level

2024-04-23 13:14 UTC, AlexandraTrifan approved these changes

2024-04-23 13:44 UTC, andrei47w requested changes

2024-04-23 13:44 UTC, andrei47w commented on gui/src/widgets/plotbufferpreviewer.cpp
> +		m_bufferPrevInitMax = m_plot->plot()->axisScaleDiv(m_plot->xAxis()->axisId()).upperBound();
replace axisScaleDiv with PlotAxis::visibleMin / PlotAxis::visibleMax

2024-04-23 13:44 UTC, andrei47w commented on gui/src/buffer_previewer.cpp
> +BufferPreviewer::~BufferPreviewer() { delete m_wavePoints; }
This alone doesn't fix the crash. m_wavePoints needs to be initialized in constructor
m_wavePoints(new QPointF)

2024-04-24 08:52 UTC, andrei47w approved these changes

2024-04-24 09:34 UTC, merged