Windows local build changes and new documentation
analogdevicesinc/scopy pull request #1641
Opened 2024-05-29 07:06 UTC by JJuanill

## Changes
**`CMakeLists.txt`**
Added post-build in CMake to copy .DLL files in build directory for launching and debugging Scopy in Windows

**`cmakelists_template.mako`**
Adjusted CMakeLists template for plugins to output generated libraries in plugins directory

## Added
**`local-windows-build-readme.md`**
Documented build process for local Windows environment

2024-05-30 12:07 UTC, bindea-cristian commented
Hi @JJuanill, I'll look into your PR in the following days

2024-05-31 13:14 UTC, bindea-cristian requested changes
Overall good documentation, good description of the workflow, a good how to get started on Scopy development.
Just few hardcoded things that can be resolved, I think a tutorial should be more generic.
And a few misunderstandings about what commands are used when creating a docker image and what commands are used in practice.
Overall good job.

2024-05-31 13:14 UTC, bindea-cristian commented on doc/local-windows-build-readme.md
> +        C:\msys64\usr\bin\bash.exe -lc "cd /home/docker/scopy-mingw-build-deps && ls && echo Building for x86_64 && ./init_staging.sh x86_64 OFF"
You don't have to copy line by line each command used in the Dockerfile, many of them are useful just in the context of creating the Docker image.
This line is not needed in the tutorial

2024-05-31 13:14 UTC, bindea-cristian commented on doc/local-windows-build-readme.md
> +        C:\msys64\usr\bin\bash.exe -lc "cd /home/docker/scopy-mingw-build-deps && source build.sh && install_tools && install_deps && recurse_submodules"
We've recently made a change inside the build.sh script and now it is possible to execute the script independent of the current location and to call the functions much easier.
This line would change to
`C:\msys64\usr\bin\bash.exe -lc "/home/docker/scopy-mingw-build-deps/build.sh install_tools install_deps recurse_submodules"`

2024-05-31 13:14 UTC, bindea-cristian commented on doc/local-windows-build-readme.md
> +        C:\msys64\usr\bin\bash.exe -lc "cd /home/docker/scopy-mingw-build-deps && source build.sh && build_deps"
The same here

2024-05-31 13:14 UTC, bindea-cristian commented on doc/local-windows-build-readme.md
> +        C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syuu" & C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syuu" & C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Scc "
These lines can be shortened to
C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syyuu"
And this would be enough for the turorial.

2024-05-31 13:46 UTC, bindea-cristian commented
And also, thank you very much for your contribution to the project! :D

2024-06-05 02:11 UTC, JJuanill commented
> And also, thank you very much for your contribution to the project! :D

Thank you too for the valuable feedback. I'll be working on these changes you raised. 😊

2024-07-12 01:23 UTC, JJuanill reviewed
Reverted code changes and revised build documentation

2024-08-07 08:31 UTC, merged