Ci automated js ctests
analogdevicesinc/scopy pull request #1660
Opened 2024-07-10 12:37 UTC by IonutMuthi

2024-07-24 10:09 UTC, adisuciu requested changes

2024-07-24 10:09 UTC, adisuciu commented on JS/scopyDefaultTests.js
> +  printToConsole("TEST SWITHC TOOL")
typo

2024-07-24 10:09 UTC, adisuciu commented on JS/scopyDefaultTests.js
> +
typo

2024-07-24 10:09 UTC, adisuciu commented on JS/scpyDefaultJsFunctions.js
> +    var  deviceID = scopy.addDevice("", "ip:127.0.0.0")
rename this to common.js or scopycommon.js

2024-07-24 10:09 UTC, adisuciu commented on pluginbase/src/scopyjs.cpp
> +QJSValue ScopyJS::importFileAs(const QString &path)
Do you have an example for this ?

2024-07-24 10:09 UTC, adisuciu commented on pluginbase/src/scopyjs.cpp
> +QJSValue ScopyJS::importFileAs(const QString &path)
I think both functions serve the same purpose .. are both needed as one just discards the return value ? you can simply not use it.

Also you can rename this to "evaluateFile"

2024-07-24 10:09 UTC, adisuciu commented on JS/scopyDefaultTests.js
> +
rename JS to js so it complies with the rest of the project

2024-08-06 13:18 UTC, adisuciu requested changes

2024-08-06 13:18 UTC, adisuciu commented on js/scpycommon.js
> +function connect(){
typo: file name

2024-08-06 13:38 UTC, AlexandraTrifan commented on js/test.sh
> +# get scopy buil path from CMakeCache.txt
"build" typo

2024-08-06 13:39 UTC, AlexandraTrifan commented on plugins/datalogger/js/dataLoggerAutomatedTest.js
> +//This import paht is relative to where scopy is build
path typo

2024-08-06 13:40 UTC, AlexandraTrifan commented on plugins/datalogger/js/dataLoggerAutomatedTest.js
> +evaluateFile("../js/scpyDefaultJsFunctions.js")
file name typo

2024-08-06 13:43 UTC, AlexandraTrifan commented on tests/CMakeLists.txt
> +		 COMMAND bash ${CMAKE_SOURCE_DIR} / js / test.sh "${CMAKE_SOURCE_DIR}/resources/emuXml/"
"${CMAKE_SOURCE_DIR} / js / test.sh" are these white spaces intentionally added?

2024-08-06 14:14 UTC, Andrei-Fabian-Pop reviewed
Could you also check the indentation in the js and bash scripts, there are some misaligned rows and extra spaces

2024-08-09 08:52 UTC, merged