Add option for selecting the debugger version
analogdevicesinc/scopy pull request #1661
Opened 2024-07-18 14:16 UTC by Andrei-Fabian-Pop

The preferences page now contains a checkbox that when selected (true) will only load the IIODebug (V2) and when it is unchecked (false) it will only load the Debugger (V1). The default is V2.

2024-07-24 10:10 UTC, adisuciu commented
I think you should merge the plugins to a single plugin with 2 instruments and the preference should be pluginspecific.

2024-07-24 10:38 UTC, adisuciu requested changes
Merge instruments to the same plugin

2024-08-20 05:41 UTC, andreidanila1 approved these changes

2024-08-20 08:08 UTC, adisuciu approved these changes

2024-08-20 08:08 UTC, merged