emu: add configurations for emulator
analogdevicesinc/scopy pull request #1677
Opened 2024-08-14 10:05 UTC by IonutMuthi

2024-08-19 09:57 UTC, andreidanila1 approved these changes

2024-08-20 08:04 UTC, adisuciu requested changes

2024-08-20 08:04 UTC, adisuciu commented on core/src/emuwidget.cpp
> +	if(option.compare("adalm2000") != 0) {
This option could be part of the xml as well .. no ?

2024-08-21 12:10 UTC, adisuciu approved these changes

2024-08-21 12:10 UTC, merged